### PR TITLE
Added icc profile routines

### LINKED ISSUE #138: [Bug]: Pics' color will be changed if contains an ICC tag.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

pic

Here is a zipped file for this issue.
[Downloads.zip](https://github.com/SalOne22/rimage/files/13194621/Downloads.zip)

### Expected behavior

Compressed the Pic with right color.

### Library Version

0.9.1

### PR DESCRIPTION
**Pull request by SalOne22**
@Mikachu2333 this PR adds support for images with icc profile. Could you check that everything work as expected now?
closes #138

### CODE REVIEW

**Comment by Mikachu2333** [comment]
图片

The first img (0047.jpg) would still change color when using default values, for example `.\rimage moz *.jpg -s _u`. And I think it may caused by the option `--dithering`. When I was about to change it  bt myself, process crashed.

图片

**Review by Mikachu2333 — CHANGES_REQUESTED** [review]
When input a bmp pic which has a icc tag and output with other codec, rimge output it with wrong color.

[bmp.zip](https://github.com/SalOne22/rimage/files/15209395/bmp.zip)

**Comment by SalOne22** [comment]
> pic's color still be changed from red to green.

I suppose that it because I apply ICC profile to srbg profile, so some colors can be loss. I will create another issue to add `--preserve` flag that will preserve ICC profile on codecs that support metadata.

> When input a bmp pic which has a icc tag and output with other codec, rimge output it with wrong color.

This is issue in `zune-bmp`, decoded image doesn't have ICC profile

**Comment by Mikachu2333** [comment]
> This is issue in `zune-bmp`, decoded image doesn't have ICC profile

Will this be fixed or just mark as a note in readme, or maybe we'd better make an issue in [Here](https://github.com/etemesi254/zune-image) ? 

> add `--preserve` flag that will preserve ICC profile on codecs that support metadata

This option is for all supported codecs (include input only codec) or just the formats that allow both input and output? And, some codecs doesn't support icc feature such as qoi etc.

**Comment by SalOne22** [comment]
> Will this be fixed or just mark as a note in readme, or maybe we'd better make an issue in [Here](https://github.com/etemesi254/zune-image) ?

Create an Issue in zune-image

> This option is for all supported codecs (include input only codec) or just the formats that allow both input and output? And, some codecs doesn't support icc feature such as qoi etc.

If input image has ICC profile and output codec supports writing ICC profile this option will preserve this as a tag in metadata. Otherwise will transform image to srgb profile or does nothing if image doesn't have ICC profile.

**Comment by Mikachu2333** [comment]
@SalOne22 icc feature in zune-bmp has been fixed.
https://github.com/etemesi254/zune-image/issues/195

**Comment by SalOne22** [comment]
Okay, while we waiting for new release of zune-image, we can merge this now, and create a new pre-release with partial icc support. This will allow usage of new features, and after new zune-image version add support for bmp files (I don't think that most of the users will face this issue, most of the images on the web are in jpg/png format)

**Comment by Mikachu2333** [comment]
ok, and I'll approve this and start to work on the _better-docs_ branch.

**Review by Mikachu2333 — APPROVED** [review]

**Review by Mikachu2333 — APPROVED** [review]

**Pull request merged**
