### PR TITLE
fix(cli/windows): fixed trailing slash cmd issue

### LINKED ISSUE #67: Add support for path-arg which end with "\"
## Description
Sorry for bother.
**Hope you could add support for file path which end with "\\".**

For example "D:\\desktop\\". Every time i use rimage and i need to delete the "\\" manually, especially when i decide to use the program for different pics in different dirs... 
Besides, many programs likes to add a "\\" after original path like "Everything" and so on.

Hope you could add a support for it!

**Additional**
I made a GUI for rimage and since I am a bit confused about the double licenses you are using, I hope you can check if it meets the requirements.
https://github.com/Mikachu2333/rimage_gui
Thanks a thousand of time!

### PR DESCRIPTION
**Pull request by SalOne22**
closes #67 
@Mikachu2333 can you check that issue is fixed?

### CODE REVIEW

**Comment by Mikachu2333** [comment]
I'll check it.

**Comment by Mikachu2333** [comment]
Fixed.

But, the -s option goes wrong and play no role when output... Maybe I'd better open another issue for this qusetion rather than discuss in this pr?
图片

**Comment by SalOne22** [comment]
This is a error of rust `args()` method, and clap parsing, I can't fix it https://github.com/rust-lang/rust/issues/72653

**Comment by Mikachu2333** [comment]
> As a fix, just place `-d` option at the end of command

thanks for answering!

**Pull request merged**
